class LoadVariables:

    def __init__(self, get_config):

        """General Variables"""
        self.icon_path = get_config['icon_path']
        self.icon_not_working_path = get_config['icon_not_working_path']
        self.icon_default_name = get_config['icon_default_name']
        self.l_application = get_config['application']

        """Applications"""
        # "": {"theme_name": ""}

        # Social Networks and Messaging
        self.a_facebook = get_config['application']['facebook']
        self.a_messenger = get_config['application']['messenger']
        self.a_whatsapp = get_config['application']['whatsapp']
        self.a_instagram = get_config['application']['instagram']
        self.a_reddit = get_config['application']['reddit']
        self.a_snapchat = get_config['application']['snapchat']
        self.a_twitter = get_config['application']['twitter']
        self.a_youtube = get_config['application']['youtube']
        self.a_tiktok = get_config['application']['tiktok']
        self.a_linkedin = get_config['application']['linkedin']
        self.a_pinterest = get_config['application']['pinterest']
        self.a_tumblr = get_config['application']['tumblr']
        self.a_telegram = get_config['application']['telegram']
        self.a_signal = get_config['application']['signal']
        self.a_wechat = get_config['application']['wechat']
        self.a_line = get_config['application']['line']
        self.a_viber = get_config['application']['viber']
        self.a_tandem = get_config['application']['tandem']
        self.a_xbox = get_config['application']['xbox']
        self.a_xbox_gamepass = get_config['application']['xbox_gamepass']
        self.a_discord = get_config['application']['discord']
        # Streaming & Music
        self.a_spotify = get_config['application']['spotify']
        self.a_youtube_music = get_config['application']['youtube_music']
        self.a_youtube_kids = get_config['application']['youtube_kids']
        self.a_amazon_video = get_config['application']['amazon_video']
        self.a_amazon_music = get_config['application']['amazon_music']
        self.a_disneyplus = get_config['application']['disneyplus']
        self.a_hulu = get_config['application']['hulu']
        self.a_netflix = get_config['application']['netflix']
        self.a_soundcloud = get_config['application']['soundcloud']
        self.a_deezer = get_config['application']['deezer']
        self.a_twitch = get_config['application']['twitch']
        self.a_vimeo = get_config['application']['vimeo']
        self.a_hbo_max = get_config['application']['hbo_max']
        self.a_soundhound = get_config['application']['soundhound']
        self.a_shazam = get_config['application']['shazam']
        self.a_musixmatch = get_config['application']['musixmatch']
        # Google apps
        self.a_g_maps = get_config['application']['g_maps']
        self.a_g_drive = get_config['application']['g_drive']
        self.a_g_earth = get_config['application']['g_earth']
        self.a_g_search = get_config['application']['g_search']
        self.a_g_mail = get_config['application']['g_mail']
        self.a_g_chrome = get_config['application']['g_chrome']
        self.a_g_playstore = get_config['application']['g_playstore']
        self.a_g_calendar = get_config['application']['g_calendar']
        self.a_g_translate = get_config['application']['g_translate']
        self.a_g_docs = get_config['application']['g_docs']
        self.a_g_sheets = get_config['application']['g_sheets']
        self.a_g_slides = get_config['application']['g_slides']
        self.a_g_meetings = get_config['application']['g_meetings']
        self.a_g_pay = get_config['application']['g_pay']
        # Microsoft Apps
        self.a_m_office = get_config['application']['m_office']
        self.a_m_outlook = get_config['application']['m_outlook']
        self.a_m_edge = get_config['application']['m_edge']
        self.a_m_word = get_config['application']['m_word']
        self.a_m_excel = get_config['application']['m_excel']
        self.a_m_powerpoint = get_config['application']['m_powerpoint']
        self.a_m_onedrive = get_config['application']['m_onedrive']
        self.a_m_teams = get_config['application']['m_teams']
        self.a_m_office_lens = get_config['application']['m_office_lens']
        self.a_m_authenticator = get_config['application']['m_authenticator']
        self.a_m_bing = get_config['application']['m_bing']
        self.a_m_swiftkey = get_config['application']['m_swiftkey']
        # Browsers and utilities
        self.a_dropbox = get_config['application']['dropbox']
        self.a_evernote = get_config['application']['evernote']
        self.a_firefox = get_config['application']['firefox']
        self.a_opera = get_config['application']['opera']
        self.a_duckduckgo = get_config['application']['duckduckgo']
        self.a_protonmail = get_config['application']['protonmail']
        self.a_brave = get_config['application']['brave']
        # Shooping
        self.a_amazon = get_config['application']['amazon']
        self.a_ebay = get_config['application']['ebay']
        self.a_aliexpress = get_config['application']['aliexpress']
        self.a_walmart = get_config['application']['walmart']
        self.a_mercadolibre = get_config['application']['mercadolibre']
        self.a_shein = get_config['application']['shein']
        self.a_ikea = get_config['application']['ikea']
        self.a_hm = get_config['application']['hm']
        self.a_zara = get_config['application']['zara']
        self.a_kavak = get_config['application']['kavak']
        # Finance and Banks
        self.a_robinhood = get_config['application']['robinhood']
        self.a_coinbase = get_config['application']['coinbase']
        self.a_bloomberg = get_config['application']['bloomberg']
        self.a_yahoo_finance = get_config['application']['yahoo_finance']
        self.a_skrill = get_config['application']['skrill']
        self.a_binance = get_config['application']['binance']
        self.a_bitso = get_config['application']['bitso']
        self.a_investingdotcom = get_config['application']['investingdotcom']
        self.a_global66 = get_config['application']['global66']
        self.a_wise = get_config['application']['wise']
        self.a_aforemovil = get_config['application']['aforemovil']
        self.a_cashi = get_config['application']['cashi']
        self.a_paypal = get_config['application']['paypal']
        self.a_bbva_mx = get_config['application']['bbva_mx']
        self.a_nu_mx = get_config['application']['nu_mx']
        self.a_amex = get_config['application']['amex']
        self.a_citibanamex_movil = get_config['application']['citibanamex_movil']
        self.a_santander_mx = get_config['application']['santander_mx']
        self.a_hsbc_mx = get_config['application']['hsbc_mx']
        self.a_banorte = get_config['application']['banorte']
        self.a_scotiabank_mx = get_config['application']['scotiabank_mx']
        self.a_inbursa = get_config['application']['inbursa']
        self.a_banco_azteca = get_config['application']['banco_azteca']
        self.a_fondeadora = get_config['application']['fondeadora']
        self.a_afirme_movil = get_config['application']['afirme_movil']
        self.a_bancoppel = get_config['application']['bancoppel']
        self.a_banjionet_movil = get_config['application']['banjionet_movil']
        self.a_banregio = get_config['application']['banregio']
        self.a_uala = get_config['application']['uala']
        self.a_klar = get_config['application']['klar']
        self.a_heybanco = get_config['application']['heybanco']
        self.a_flink = get_config['application']['flink']
        self.a_clip = get_config['application']['clip']
        self.a_mercadopago = get_config['application']['mercadopago']
        self.a_spin = get_config['application']['spin']
        self.a_undostres = get_config['application']['undostres']
        self.a_albo = get_config['application']['albo']
        # Transport
        self.a_uber = get_config['application']['uber']
        self.a_didi = get_config['application']['didi']
        self.a_indriver = get_config['application']['indriver']
        self.a_blablacar = get_config['application']['blablacar']
        self.a_ado_movil = get_config['application']['ado_movil']
        # Travel
        self.a_airbnb = get_config['application']['airbnb']
        self.a_bookingdotcom = get_config['application']['bookingdotcom']
        self.a_tripadvisor = get_config['application']['tripadvisor']
        self.a_hostelworld = get_config['application']['hostelworld']
        self.a_couchsurfing = get_config['application']['couchsurfing']
        self.a_loungkey = get_config['application']['loungkey']
        self.a_prioritypass = get_config['application']['prioritypass']
        self.a_eventbride = get_config['application']['eventbride']
        self.a_meetup = get_config['application']['meetup']
        # Delivery
        self.a_uber_eats = get_config['application']['uber_eats']
        self.a_rappi = get_config['application']['rappi']
        self.a_didi_food = get_config['application']['didi_food']
        self.a_dominos_mx = get_config['application']['dominos_mx']
        self.a_pizza_hut_mx = get_config['application']['pizza_hut_mx']
        self.a_mi_oxxo = get_config['application']['mi_oxxo']
        # Educational
        self.a_duolingo = get_config['application']['duolingo']
        self.a_coursera = get_config['application']['coursera']
        self.a_udemy = get_config['application']['udemy']
        self.a_babbel = get_config['application']['babbel']

